# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZlWd_jhIGOQc90ofiKK7UWmP9Nmu37S
"""

!pip install -q streamlit pyngrok PyPDF2 langchain-community google-genai opencv-python numpy

# Commented out IPython magic to ensure Python compatibility.
# %%writefile chatapp.py
# import streamlit as st
# from PyPDF2 import PdfReader
# from langchain.text_splitter import RecursiveCharacterTextSplitter
# from langchain_community.vectorstores import FAISS
# from langchain_community.chat_models import ChatGoogleGenerativeAI
# from langchain.chains.question_answering import load_qa_chain
# from langchain.prompts import PromptTemplate
# from langchain_community.embeddings import GoogleGenerativeAIEmbeddings
# import os
# 
# GOOGLE_API_KEY = "AIzaSyDSO-1IXDnJZW5SYETGPjaXVC3nKYtdzic"
# os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY
# 
# def get_pdf_text(pdf_docs):
#     text = ""
#     for pdf in pdf_docs:
#         pdf_reader = PdfReader(pdf)
#         for page in pdf_reader.pages:
#             text += page.extract_text()
#     return text
# 
# def get_text_chunks(text):
#     text_splitter = RecursiveCharacterTextSplitter(chunk_size=5000, chunk_overlap=500)
#     chunks = text_splitter.split_text(text)
#     return chunks
# 
# def get_vector_store(text_chunks):
#     embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001")
#     vector_store = FAISS.from_texts(text_chunks, embedding=embeddings)
#     vector_store.save_local("faiss_index")
# 
# def get_conversational_chain():
#     prompt_template = """
# Answer the question as detailed as possible from the provided context.
# If the answer is not in the provided context, just say "Answer not available in the context."
# 
# Context:\n{context}\n
# Question:\n{question}\n
# Answer:
# """
#     model = ChatGoogleGenerativeAI(model="gemini-pro", temperature=0.3)
#     prompt = PromptTemplate(template=prompt_template, input_variables=["context", "question"])
#     chain = load_qa_chain(model, chain_type="stuff", prompt=prompt)
#     return chain
# 
# def user_input(user_question):
#     embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001")
#     new_db = FAISS.load_local("faiss_index", embeddings)
#     docs = new_db.similarity_search(user_question)
#     chain = get_conversational_chain()
#     response = chain({"input_documents": docs, "question": user_question}, return_only_outputs=True)
#     st.write("Reply: ", response["output_text"])
# 
# def main():
#     st.set_page_config("Multi PDF Chatbot", page_icon=":scroll:")
#     st.header("Multi-PDF's 📚 - Chat Agent 🤖")
# 
#     user_question = st.text_input("Ask a Question from the PDF Files uploaded .. ✍️📝")
#     if user_question:
#         user_input(user_question)
# 
#     with st.sidebar:
#         st.title("📁 PDF File Section")
#         pdf_docs = st.file_uploader("Upload PDF Files & Click Submit & Process", accept_multiple_files=True)
#         if st.button("Submit & Process"):
#             with st.spinner("Processing PDFs..."):
#                 raw_text = get_pdf_text(pdf_docs)
#                 text_chunks = get_text_chunks(raw_text)
#                 get_vector_store(text_chunks)
#                 st.success("Processing Done! PDFs ready for Q&A.")
# 
# if __name__ == "__main__":
#     main()
#

